#!/usr/bin/env python3
"""Emit MediaMTX yaml: one origin publisher + cam0..cam29 pulling it."""
from __future__ import annotations

import os

CAMERA_COUNT = int(os.environ.get("CAMERA_COUNT", "30"))
FFMPEG = (
    "ffmpeg -hide_banner -loglevel warning -re -f lavfi "
    "-i testsrc2=size=2560x1440:rate=25 -an -c:v libx264 -preset ultrafast "
    "-tune zerolatency -threads 4 -profile:v high -level:v 5.1 -pix_fmt yuv420p "
    "-g 25 -bf 0 -x264-params repeat-headers=1:keyint=25:min-keyint=25 "
    "-bsf:v h264_mp4toannexb,dump_extra=freq=keyframe "
    "-b:v 4M -maxrate 4M -bufsize 2M "
    "-f rtsp -rtsp_transport tcp rtsp://127.0.0.1:8554/origin"
)

print(
    f"""# Generated by generate_mediamtx.py — do not edit by hand.
# origin = single 1440p25 encode. camN = isolated fan-out for camera index N.
logLevel: info
logDestinations: [stdout]
readTimeout: 30s
writeTimeout: 30s
writeQueueSize: 2048
rtsp: true
rtspTransports: [tcp]
rtspAddress: :8554
rtmp: false
hls: false
webrtc: false
srt: false
moq: false
playback: false
api: true
apiAddress: :9997
metrics: true
metricsAddress: :9998
paths:
  origin:
    runOnInit: '{FFMPEG}'
    runOnInitRestart: true
  live:
    source: rtsp://127.0.0.1:8554/origin
    sourceOnDemand: false
    maxReaders: 0
"""
)
for i in range(CAMERA_COUNT):
    print(f"  cam{i}:")
    print("    source: rtsp://127.0.0.1:8554/origin")
    print("    sourceOnDemand: false")
    print("    maxReaders: 0")

